name: Atualizar Dados COVID-19

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn requests
        
    - name: Executar script
      run: python covid_dashboard.py
      
    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Commitar e publicar
      run: |
        git add .
        git commit -m "📊 Atualização automática - $(date +'%d/%m/%Y')" || echo "Sem mudanças"
        git push 